name: Cafezinho do Seguro

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  enviar-email:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar o Cafezinho
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
        run: python script.py
